### ISSUE TITLE
Databricks database access issue

### ISSUE THREAD

**Issue by lcpinheiro** [darwin-eu/CDMConnector#3] opened 2023-03-16 08:14 UTC
The `generateCohortSet()` function, calling a Spark DB on Databricks, through an ODBC connection threw the error below:

```
cdm <- generateCohortSet(cdm, ma_cohort_set, name = "ma", computeAttrition = TRUE, 
    overwrite = TRUE)
Error in connection_begin(conn@ptr) : 
  nanodbc/nanodbc.cpp:1199: HYC00: [Simba][ODBC] (11470) Transactions are not supported. 
```

I have disabled the "Enable translation for CTAS" option on the ODBC Data Source Administration, but this didn't sort the issue.

Any suggestions?

**Comment by ablack3** [comment] 2023-03-23 15:37
Thank you for reporting this @lcpinheiro. I'll do some digging.

**Comment by ablack3** [comment] 2023-03-24 17:21
Hi @lcpinheiro,

I found an issue with comments in the SQL code generated by the OHDSI tools for cohort generation. I've made some changes to CDMConnector to try and fix this and have a working reprex for you to try. 

Please install the new branch I created for this issue `remotes::install_github("OdyOSG/CDMConnector", ref = "issue_122")` (had to change the number) and try running the example below.

``` r
# install the branch for this issue
# remotes::install_github("OdyOSG/CDMConnector", ref = "issue_122")

library(CDMConnector)
con <- DBI::dbConnect(odbc::odbc(), dsn = "Databricks")

writeSchema <- "omop531results"
cdmSchema <- "omop531"

cdm <- cdmFromCon(con,
                  cdmSchema = cdmSchema,
                  cdmTables = tbl_group("default"),
                  writeSchema = writeSchema)

cohortSet <- readCohortSet(system.file("cohorts2", package = "CDMConnector", mustWork = TRUE))[3,]

cdm <- generateCohortSet(cdm,
                         cohortSet,
                         name = "chrt0",
                         computeAttrition = TRUE,
                         overwrite = TRUE)


cdm$chrt0
#> # Source:   table<`omop531results`.`chrt0`> [0 x 4]
#> # Database: Spark SQL 3.2.1[token@Spark SQL/hive_metastore]
#> # … with 4 variables: cohort_definition_id <int>, subject_id <int64>,
#> #   cohort_start_date <date>, cohort_end_date <date>
cohort_set(cdm$chrt0)
#> # Source:   table<`omop531results`.`chrt0_set`> [1 x 2]
#> # Database: Spark SQL 3.2.1[token@Spark SQL/hive_metastore]
#>   cohort_definition_id cohort_name 
#>                  <int> <chr>       
#> 1                    3 GIBleed_male
DBI::dbDisconnect(con)
```

<sup>Created on 2023-03-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ablack3** [comment] 2023-03-28 20:46
@lcpinheiro Any update?

**Comment by lcpinheiro** [comment] 2023-03-31 06:27
Hey @ablack3, Thanks! I'll be looking at it today. Let you know shortly!

**Comment by lcpinheiro** [comment] 2023-03-31 15:54
Hi @ablack3, 

Just an update, I still have the same error. There seems to be an issue with this bit of code in the `cdmFromCon()` function.

```
  df1 <- data.frame(chr_col = "a", numeric_col = 1)
  # ROracle does not support integer round trip
  DBI::dbWriteTable(con, DBI::SQL(tablename), df1)

  withr::with_options(list(databaseConnectorIntegerAsNumeric = FALSE), {
    df2 <- DBI::dbReadTable(con, DBI::SQL(tablename))
    names(df2) <- tolower(names(df2))
  })

```
It could be a setting from our side. Will get back to this next week.

**Comment by ablack3** [comment] 2023-04-04 15:00
Ok let me check again.

**Comment by lcpinheiro** [comment] 2023-04-04 17:30
Hey @ablack3,

Your solution seems to work. The different issue that I raised (https://github.com/darwin-eu/CDMConnector/issues/3#issuecomment-1492182896) is related to choosing "Use native query" in the ODBC settings. Once removed the issue goes away. Databricks seems to have a bit of a problem with using native query, in JDBC it's required, in ODBC it seems detrimental.

I did have an issue with the `cdmFromCon()` function: 

```
> cdm <- cdm_from_con(con,
+                   cdmSchema = cdmSchema,
+                   cdmTables = tbl_group("default"),
+                   writeSchema = writeSchema)
Error in cdm_from_con(con, cdmSchema = cdmSchema, cdmTables = tbl_group("default"),  : 
  unused arguments (cdmSchema = cdmSchema, cdmTables = tbl_group("default"), writeSchema = writeSchema)
> cdm <- cdmFromCon(con,
+                   cdmSchema = cdmSchema,
+                   cdmTables = tbl_group("default"),
+                   writeSchema = writeSchema)
> 
```

**Comment by ablack3** [comment] 2023-04-04 17:47
Thanks for the info. what is a "native query"?

For `cdm_from_con` the argument names also need to be snake case.
```
cdm <- cdm_from_con(con,
                   cdm_schema = cdmSchema,
                   cdm_tables = tbl_group("default"),
                   write_schema = writeSchema)
```

**Comment by ablack3** [comment] 2023-06-02 10:11
Closing this and assuming the issue is fixed. Reopen if needed.

**Closed by ablack3** 2023-06-02 10:11 UTC
